name       : haskell-GLUT
version    : 2.7.0.10
release    : 2
source     :
    - http://hackage.haskell.org/package/GLUT-2.7.0.10/GLUT-2.7.0.10.tar.gz : 4b11cbf9b7876c0ec14bf0673006bd23e7ffc7d396568987b326a1b706497569
license    : BSD-3-Clause
component  : programming.python
summary    : A Haskell binding for the OpenGL Utility Toolkit, a window system independent
    toolkit for writing OpenGL programs.
description: |
    A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-cabal-install
    - haskell-OpenGL
    - haskell-OpenGLRaw
    - haskell-random
    - haskell-StateVar
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
