name       : haskell-GLUT
version    : 2.7.0.10
release    : 1
source     :
    - http://hackage.haskell.org/package/GLUT-2.7.0.10/GLUT-2.7.0.10.tar.gz : 4b11cbf9b7876c0ec14bf0673006bd23e7ffc7d396568987b326a1b706497569
license    : BSD-3-Clause
component  : programming
summary    : A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
description: |
    A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-OpenGL
    - haskell-OpenGLRaw
    - haskell-random
    - haskell-StateVar
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 GLUT-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/GLUT-$version.conf
