name       : haskell-GLUT
version    : 2.7.0.15
release    : 5
source     :
    - https://hackage.haskell.org/package/GLUT-2.7.0.15/GLUT-2.7.0.15.tar.gz : e99527f965849756e99b132fd6975747ec0952476454e0b9ec90526e9cdde108
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
description: |
    A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
builddeps  :
    - haskell-cabal-install
    - haskell-OpenGL-devel
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-OpenGL-devel
        - haskell-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
