name       : haskell-GLUT
version    : 2.7.0.13
release    : 4
source     :
    - https://hackage.haskell.org/package/GLUT-2.7.0.13/GLUT-2.7.0.13.tar.gz : 3d217c0ee5e040992ebc278f5e20911460202a6e13767c8a0ddb01ef4adabac8
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
description: |
    A Haskell binding for the OpenGL Utility Toolkit, a window system independent toolkit for writing OpenGL programs.
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-cabal-install
    - haskell-OpenGL
    - haskell-OpenGLRaw
    - haskell-random
    - haskell-StateVar
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
